version: '3.8'

services:
  fail2ban:
    image: crazymax/fail2ban:latest
    container_name: fail2ban
    restart: unless-stopped
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - fail2ban-data:/data
      - /var/log:/var/log:ro
      - /var/log/fail2ban:/var/log/fail2ban
    environment:
      - TZ=${TZ:-America/New_York}
      - F2B_LOG_LEVEL=INFO
      - F2B_LOG_TARGET=STDOUT
      - F2B_DB_PURGE_AGE=30d
    labels:
      - "com.homeserver.service=fail2ban"
      - "com.homeserver.managed=true"

volumes:
  fail2ban-data:
    driver: local
